drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

CREATE TABLE article (
     anum int NOT NULL AUTO_INCREMENT,
     title varchar(50) DEFAULT NULL,
     description varchar(200) DEFAULT NULL,
     aname varchar(10) DEFAULT NULL,
     hit int DEFAULT NULL,
     date date DEFAULT NULL,
     PRIMARY KEY (`anum`),
     FOREIGN KEY (`aname`) REFERENCES `member` (`username`)
)

CREATE TABLE `chatroom` (
    `roomId` bigint NOT NULL AUTO_INCREMENT,
    `username` varchar(200) DEFAULT NULL,
    `artist` varchar(100) DEFAULT NULL,
    `anum` int DEFAULT NULL,
    PRIMARY KEY (`roomId`),
    FOREIGN KEY (`anum`) REFERENCES `article` (`anum`)
)